# Generated by Django 4.2 on 2023-04-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='static/pics')),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price', models.IntegerField()),
            ],
        ),
    ]
