# Generated by Django 4.2 on 2023-07-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_prod_img_alter_prod_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
